upstream mydb { server 127.0.0.1:5432; }

server {
    listen 5432 ssl;
    ssl_certificate /etc/letsencrypt/live/udhay.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/udhay.dev/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    allow ip-1/32;
    allow ip-2/32;
    deny  all;
    proxy_pass mydb;
    proxy_timeout 600s;
}
