server {
    listen 80;
    server_name udhay.dev;

    location /.well-known/acme-challenge/ {
        root C:/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name udhay.dev;

    ssl_certificate     C:/nginx/certs/udhay.dev-chain.pem;
    ssl_certificate_key C:/nginx/certs/udhay.dev-key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    add_header Strict-Transport-Security "max-age=31536000" always;

    auth_basic           "Login"; # Will be ignored by modern browsers
    auth_basic_user_file C:/nginx/htpasswd;

    location / {
        proxy_pass            http://127.0.0.1:9000;
        proxy_http_version    1.1;
        proxy_set_header      Host $host;
        proxy_set_header      X-Real-IP $remote_addr;
        proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600s;
        proxy_read_timeout    600s;
        proxy_send_timeout    600s;
    }

    access_log C:/nginx/logs/access.log;
    error_log  C:/nginx/logs/error.log;
}